-- ============================================
-- Supabase Keep-Alive Table Setup
-- ============================================
-- Run this SQL in your Supabase SQL Editor
-- This creates a table that will be queried to keep your project active
-- ============================================

-- Create keep-alive table
CREATE TABLE IF NOT EXISTS "keep-alive" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NULL DEFAULT ''::TEXT,
  random UUID NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NULL DEFAULT NOW(),
  CONSTRAINT "keep-alive_pkey" PRIMARY KEY (id)
);

-- Insert initial data
INSERT INTO "keep-alive" (name)
VALUES 
  ('placeholder'),
  ('initial-record');

-- Optional: Create index for better performance
CREATE INDEX IF NOT EXISTS idx_keep_alive_created_at ON "keep-alive" (created_at DESC);

-- Grant access to anon and authenticated users (adjust as needed)
ALTER TABLE "keep-alive" ENABLE ROW LEVEL SECURITY;

-- Allow anonymous reads (required for the keep-alive endpoint to work)
CREATE POLICY "Allow anonymous read access"
ON "keep-alive"
FOR SELECT
TO anon
USING (true);

-- Optional: Allow authenticated users to insert
CREATE POLICY "Allow authenticated insert access"
ON "keep-alive"
FOR INSERT
TO authenticated
WITH CHECK (true);
